/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.core.snippets;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.core.snippets.SnippetJ2EEGetProcessList;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class SnippetJ2EEGetProcessListEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SnippetJ2EEGetProcessList snippetJ2EEGetProcessList0 = new SnippetJ2EEGetProcessList();
      assertNotNull(snippetJ2EEGetProcessList0);
  }
}
