/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.ide.eclipse.axis.proxy;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.ide.eclipse.axis.proxy.AxisTransportClientProperties;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestAxisTransportClientProperties {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AxisTransportClientProperties axisTransportClientProperties0 = new AxisTransportClientProperties();
  }
}
