/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.lavalamp.site.impl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.IOException;
import net.sf.lavalamp.site.Build;
import net.sf.lavalamp.site.DummyRemoteGetter;
import net.sf.lavalamp.site.Getter;
import net.sf.lavalamp.site.LoginRequiredException;
import net.sf.lavalamp.site.impl.Bamboo3RestApi;
import net.sf.lavalamp.site.impl.BambooRestApi;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestBambooRestApi {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Bamboo3RestApi bamboo3RestApi0 = new Bamboo3RestApi();
      DummyRemoteGetter dummyRemoteGetter0 = new DummyRemoteGetter();
      bamboo3RestApi0.setUrlGetter((Getter) dummyRemoteGetter0);
      Build build0 = new Build("");
      boolean boolean0 = bamboo3RestApi0.wasLastBuildSuccessful(build0);
      assertEquals(false, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      BambooRestApi bambooRestApi0 = new BambooRestApi();
      Build build0 = new Build("s*$t");
      // Undeclared exception!
      try {
        bambooRestApi0.wasLastBuildSuccessful(build0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
