/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.ide.eclipse.server.control;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.ide.eclipse.server.control.SapNWPublishTask;
import java.util.List;
import java.util.ResourceBundle;
import org.eclipse.wst.server.core.IServer;
import org.eclipse.wst.server.core.model.PublishOperation;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class SapNWPublishTaskEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SapNWPublishTask sapNWPublishTask0 = new SapNWPublishTask();
      List<String> list0 = ResourceBundle.Control.FORMAT_PROPERTIES;
      // Undeclared exception!
      try {
        sapNWPublishTask0.getTasks((IServer) null, (-3), (List) list0, (List) list0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      SapNWPublishTask sapNWPublishTask0 = new SapNWPublishTask();
      PublishOperation[] publishOperationArray0 = sapNWPublishTask0.getTasks((IServer) null, (-3), (List) null, (List) null);
      assertNull(publishOperationArray0);
  }
}
