/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.ide.eclipse.server.control;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.ide.eclipse.server.control.SapNWLaunchConfigurationTabGroup;
import org.eclipse.debug.ui.ILaunchConfigurationDialog;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class SapNWLaunchConfigurationTabGroupEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SapNWLaunchConfigurationTabGroup sapNWLaunchConfigurationTabGroup0 = new SapNWLaunchConfigurationTabGroup();
      sapNWLaunchConfigurationTabGroup0.createTabs((ILaunchConfigurationDialog) null, "");
  }
}
