/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.ide.eclipse.server.control;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.ide.eclipse.server.control.SapNWSourcePathComputerDelegate;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestSapNWSourcePathComputerDelegate {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SapNWSourcePathComputerDelegate sapNWSourcePathComputerDelegate0 = new SapNWSourcePathComputerDelegate();
      assertNotNull(sapNWSourcePathComputerDelegate0);
  }
}
