/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.J2EEPSTATE;
import java.io.ObjectStreamException;
import javax.xml.namespace.QName;
import org.apache.axis.description.TypeDesc;
import org.apache.axis.encoding.ser.EnumDeserializer;
import org.apache.axis.encoding.ser.EnumSerializer;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class J2EEPSTATEEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      J2EEPSTATE j2EEPSTATE0 = new J2EEPSTATE("");
      assertNotNull(j2EEPSTATE0);
      assertEquals("", j2EEPSTATE0.getValue());
  }

  @Test
  public void test1()  throws Throwable  {
      Class<?> class0 = J2EEPSTATE.class;
      QName qName0 = new QName("");
      EnumDeserializer enumDeserializer0 = (EnumDeserializer)J2EEPSTATE.getDeserializer(")fSc:(n`+g%^A>!H", (Class) class0, qName0);
      assertEquals(false, enumDeserializer0.componentsReady());
  }

  @Test
  public void test2()  throws Throwable  {
      J2EEPSTATE j2EEPSTATE0 = J2EEPSTATE.value6;
      int int0 = j2EEPSTATE0.hashCode();
      assertEquals(1177598144, int0);
  }

  @Test
  public void test3()  throws Throwable  {
      J2EEPSTATE j2EEPSTATE0 = J2EEPSTATE.fromString("");
      assertNotNull(j2EEPSTATE0);
      
      J2EEPSTATE j2EEPSTATE1 = (J2EEPSTATE)j2EEPSTATE0.readResolve();
      assertNotNull(j2EEPSTATE1);
      assertSame(j2EEPSTATE0, j2EEPSTATE1);
      assertEquals("", j2EEPSTATE1.toString());
  }

  @Test
  public void test4()  throws Throwable  {
      TypeDesc typeDesc0 = J2EEPSTATE.getTypeDesc();
      assertEquals(false, typeDesc0.hasAttributes());
  }

  @Test
  public void test5()  throws Throwable  {
      J2EEPSTATE j2EEPSTATE0 = J2EEPSTATE.fromString("");
      assertNotNull(j2EEPSTATE0);
      
      String string0 = j2EEPSTATE0.getValue();
      assertNotNull(string0);
      assertEquals("", string0);
  }

  @Test
  public void test6()  throws Throwable  {
      Class<?> class0 = J2EEPSTATE.class;
      QName qName0 = new QName("");
      EnumSerializer enumSerializer0 = (EnumSerializer)J2EEPSTATE.getSerializer("", (Class) class0, qName0);
      assertEquals("Axis SAX Mechanism", enumSerializer0.getMechanismType());
  }

  @Test
  public void test7()  throws Throwable  {
      try {
        J2EEPSTATE.fromString(";l=~|\"Z9k\n3E");
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
      }
  }

  @Test
  public void test8()  throws Throwable  {
      J2EEPSTATE j2EEPSTATE0 = J2EEPSTATE.fromString("");
      assertNotNull(j2EEPSTATE0);
      
      J2EEPSTATE j2EEPSTATE1 = J2EEPSTATE.value2;
      boolean boolean0 = j2EEPSTATE0.equals((Object) j2EEPSTATE1);
      assertEquals(false, boolean0);
      assertEquals("", j2EEPSTATE0.getValue());
  }

  @Test
  public void test9()  throws Throwable  {
      J2EEPSTATE j2EEPSTATE0 = J2EEPSTATE.value7;
      boolean boolean0 = j2EEPSTATE0.equals((Object) j2EEPSTATE0);
      assertEquals(true, boolean0);
  }
}
