/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class J2EEClusterMsgEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg("6D:;dt", "6D:;dt", 1073741808L, 1073741808L, 1073741808L, 1073741808L, 1073741808L, 1073741808L, 1073741808L, 1073741808L, 1073741808L);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg("n4", "n4", 1859L, 1859L, 1859L, 1859L, 1859L, 1859L, 1859L, 1859L, 1859L);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try {
        J2EEClusterMsg.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      Class<?> class0 = Class.class;
      QName qName0 = new QName("nv(T$K", "nv(T$K");
      // Undeclared exception!
      try {
        J2EEClusterMsg.getSerializer("nv(T$K", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      Class<?> class0 = J2EEClusterMsg.class;
      QName qName0 = new QName("", "", "");
      // Undeclared exception!
      try {
        J2EEClusterMsg.getDeserializer("", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg("n4", "n4", 1859L, 1859L, 1859L, 1859L, 1859L, 1859L, 1859L, 1859L, 1859L);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg((String) null, (String) null, (-796L), (-796L), (-796L), (-796L), 740L, (-796L), 740L, 740L, (-796L));
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg("n4", "n4", 1859L, 1859L, 1859L, 1859L, 1859L, 1859L, 1859L, 1859L, 1859L);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg("0", (String) null, 1073741812L, 1073741812L, 1073741812L, 1073741812L, 1073741812L, 1073741812L, 1073741812L, 1073741812L, 1073741812L);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test18()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg("n4", "n4", 1859L, 1859L, 1859L, 1859L, 1859L, 1859L, 1859L, 1859L, 1859L);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test19()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test20()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test21()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test22()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test23()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }

  @Test
  public void test24()  throws Throwable  {
      J2EEClusterMsg j2EEClusterMsg0 = null;
      try {
        j2EEClusterMsg0 = new J2EEClusterMsg();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEClusterMsg
         */
      }
  }
}
