/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.LogFile;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestLogFile {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile("5g~", (-69L), "5g~", "5g~");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Class<?> class0 = LogFile.class;
      // Undeclared exception!
      try {
        LogFile.getSerializer("N~oOqm", (Class) class0, (QName) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile("zEzCe", 1048578L, "zEzCe", "zEzCe");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile("2@_2D6e+ pUe", (-1021L), "2@_2D6e+ pUe", "2@_2D6e+ pUe");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile("2@_2D6e+ pUe", (-1021L), "2@_2D6e+ pUe", "2@_2D6e+ pUe");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      Class<?> class0 = LogFile.class;
      // Undeclared exception!
      try {
        LogFile.getDeserializer("N~oOqm", (Class) class0, (QName) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      // Undeclared exception!
      try {
        LogFile.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile("{1'}]9`=/}@7%*K~m", 0L, "{1'}]9`=/}@7%*K~m", "{1'}]9`=/}@7%*K~m");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile("5g~", (-69L), "5g~", "5g~");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile("y]Xze", (-208L), "y]Xze", "y]Xze");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile("zEzCe", 1048578L, "zEzCe", "zEzCe");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile("{1'}]9`=/}@7%*K~m", 0L, "{1'}]9`=/}@7%*K~m", "{1'}]9`=/}@7%*K~m");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      LogFile logFile0 = null;
      try {
        logFile0 = new LogFile();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.LogFile
         */
      }
  }
}
