/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestICMProxyConnection {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection("", "", "", 823, "", 823, "", 823, 823, "", "", "", (Integer) 823, "", "", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection("org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl", 823, "org.apache.commons.logging.impl.LogFactoryImpl", 823, "org.apache.commons.logging.impl.LogFactoryImpl", 823, 823, "org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl", (Integer) 823, "org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      Class<?> class0 = QName.class;
      QName qName0 = new QName("org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl");
      // Undeclared exception!
      try {
        ICMProxyConnection.getDeserializer("org.apache.commons.logging.impl.LogFactoryImpl", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      // Undeclared exception!
      try {
        ICMProxyConnection.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection("O,0|_;rvAf!c?'zhem;", "O,0|_;rvAf!c?'zhem;", "O,0|_;rvAf!c?'zhem;", 823, "O,0|_;rvAf!c?'zhem;", 823, "O,0|_;rvAf!c?'zhem;", 823, 823, "O,0|_;rvAf!c?'zhem;", "O,0|_;rvAf!c?'zhem;", "O,0|_;rvAf!c?'zhem;", (Integer) 823, "O,0|_;rvAf!c?'zhem;", "O,0|_;rvAf!c?'zhem;", "O,0|_;rvAf!c?'zhem;", "O,0|_;rvAf!c?'zhem;");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      Class<?> class0 = QName.class;
      QName qName0 = new QName("lang", "lang", "lang");
      // Undeclared exception!
      try {
        ICMProxyConnection.getSerializer("lang", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection("", "", "", 823, "", 823, "", 823, 823, "", "", "", (Integer) 823, "", "", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test18()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test19()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection("", "", "", 823, "", 823, "", 823, 823, "", "", "", (Integer) 823, "", "", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test20()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection("org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl", 823, "org.apache.commons.logging.impl.LogFactoryImpl", 823, "org.apache.commons.logging.impl.LogFactoryImpl", 823, 823, "org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl", (Integer) 823, "org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl", "org.apache.commons.logging.impl.LogFactoryImpl");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test21()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test22()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test23()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection("l)L+wQY-}5X#%/pvg7", "l)L+wQY-}5X#%/pvg7", "l)L+wQY-}5X#%/pvg7", (-2147483636), "l)L+wQY-}5X#%/pvg7", (-2147483636), "l)L+wQY-}5X#%/pvg7", (-2147483636), 1077, "l)L+wQY-}5X#%/pvg7", "l)L+wQY-}5X#%/pvg7", "l)L+wQY-}5X#%/pvg7", (Integer) (-2147483636), "l)L+wQY-}5X#%/pvg7", "l)L+wQY-}5X#%/pvg7", "l)L+wQY-}5X#%/pvg7", "l)L+wQY-}5X#%/pvg7");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test24()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection("M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", 823, "M[[HtQ8^}y(Z6'o>", 823, "M[[HtQ8^}y(Z6'o>", 823, 823, "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", (Integer) 823, "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test25()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection("M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", 823, "M[[HtQ8^}y(Z6'o>", 823, "M[[HtQ8^}y(Z6'o>", 823, 823, "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", (Integer) 823, "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test26()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test27()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection("", "", "", 835, "", 835, "", 835, 835, "", "", "", (Integer) 835, "", "", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test28()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test29()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test30()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test31()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection("M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", 823, "M[[HtQ8^}y(Z6'o>", 823, "M[[HtQ8^}y(Z6'o>", 823, 823, "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", (Integer) 823, "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>", "M[[HtQ8^}y(Z6'o>");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }

  @Test
  public void test32()  throws Throwable  {
      ICMProxyConnection iCMProxyConnection0 = null;
      try {
        iCMProxyConnection0 = new ICMProxyConnection();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMProxyConnection
         */
      }
  }
}
