/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestInstanceProperty {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      QName qName0 = new QName("u");
      Class<?> class0 = InstanceProperty.class;
      // Undeclared exception!
      try {
        InstanceProperty.getDeserializer("u", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      InstanceProperty instanceProperty0 = null;
      try {
        instanceProperty0 = new InstanceProperty("g+S%e_|5q9y,xyp", "g+S%e_|5q9y,xyp", "g+S%e_|5q9y,xyp");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      QName qName0 = QName.valueOf("9s");
      Class<?> class0 = InstanceProperty.class;
      // Undeclared exception!
      try {
        InstanceProperty.getSerializer("9s", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try {
        InstanceProperty.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      InstanceProperty instanceProperty0 = null;
      try {
        instanceProperty0 = new InstanceProperty();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      InstanceProperty instanceProperty0 = null;
      try {
        instanceProperty0 = new InstanceProperty();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      InstanceProperty instanceProperty0 = null;
      try {
        instanceProperty0 = new InstanceProperty("g+S%e_|5q9y,xyp", "g+S%e_|5q9y,xyp", "g+S%e_|5q9y,xyp");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      InstanceProperty instanceProperty0 = null;
      try {
        instanceProperty0 = new InstanceProperty();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      InstanceProperty instanceProperty0 = null;
      try {
        instanceProperty0 = new InstanceProperty();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      InstanceProperty instanceProperty0 = null;
      try {
        instanceProperty0 = new InstanceProperty();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      InstanceProperty instanceProperty0 = null;
      try {
        instanceProperty0 = new InstanceProperty("9s", "9s", "9s");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      InstanceProperty instanceProperty0 = null;
      try {
        instanceProperty0 = new InstanceProperty();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      InstanceProperty instanceProperty0 = null;
      try {
        instanceProperty0 = new InstanceProperty();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      InstanceProperty instanceProperty0 = null;
      try {
        instanceProperty0 = new InstanceProperty();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceProperty
         */
      }
  }
}
