/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.ParameterRestriction;
import com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter;
import com.sap.managementconsole.soap.axis.sapcontrol.RESTRICTIONTYPE;
import com.sap.managementconsole.soap.axis.sapcontrol.SubProfileParameter;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestProfileParameter {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RESTRICTIONTYPE rESTRICTIONTYPE0 = null;
      try {
        rESTRICTIONTYPE0 = RESTRICTIONTYPE.value1;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test1()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try {
        ProfileParameter.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      Class<?> class0 = ProfileParameter.class;
      QName qName0 = QName.valueOf("\" options.");
      // Undeclared exception!
      try {
        ProfileParameter.getDeserializer("\" options.", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      SubProfileParameter[] subProfileParameterArray0 = new SubProfileParameter[1];
      String[] stringArray0 = new String[9];
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter("", "", "", "", (ParameterRestriction) null, subProfileParameterArray0, "", "", stringArray0, stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      Class<?> class0 = ProfileParameter.class;
      QName qName0 = QName.valueOf("\" options.");
      // Undeclared exception!
      try {
        ProfileParameter.getSerializer("\" options.", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      RESTRICTIONTYPE rESTRICTIONTYPE0 = null;
      try {
        rESTRICTIONTYPE0 = RESTRICTIONTYPE.value6;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test14()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      SubProfileParameter[] subProfileParameterArray0 = new SubProfileParameter[1];
      String[] stringArray0 = new String[7];
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter("\" has no closing brace. Opening raceat position ", "\" has no closing brace. Opening raceat position ", "\" has no closing brace. Opening raceat position ", "\" has no closing brace. Opening raceat position ", (ParameterRestriction) null, subProfileParameterArray0, "\" has no closing brace. Opening raceat position ", "\" has no closing brace. Opening raceat position ", stringArray0, stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test18()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test19()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test20()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test21()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test22()  throws Throwable  {
      SubProfileParameter[] subProfileParameterArray0 = new SubProfileParameter[1];
      String[] stringArray0 = new String[7];
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter("", "", "", "", (ParameterRestriction) null, subProfileParameterArray0, "", "", (String[]) null, stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test23()  throws Throwable  {
      SubProfileParameter[] subProfileParameterArray0 = new SubProfileParameter[1];
      String[] stringArray0 = new String[7];
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter("\" has no closing brace. Opening raceat position ", "\" has no closing brace. Opening raceat position ", "\" has no closing brace. Opening raceat position ", "\" has no closing brace. Opening raceat position ", (ParameterRestriction) null, subProfileParameterArray0, "\" has no closing brace. Opening raceat position ", "\" has no closing brace. Opening raceat position ", stringArray0, stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test24()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test25()  throws Throwable  {
      ProfileParameter profileParameter0 = null;
      try {
        profileParameter0 = new ProfileParameter();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ProfileParameter
         */
      }
  }

  @Test
  public void test26()  throws Throwable  {
      RESTRICTIONTYPE rESTRICTIONTYPE0 = null;
      try {
        rESTRICTIONTYPE0 = RESTRICTIONTYPE.value1;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test27()  throws Throwable  {
      ParameterRestriction parameterRestriction0 = null;
      try {
        parameterRestriction0 = new ParameterRestriction();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ParameterRestriction
         */
      }
  }
}
