/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.STATECOLOR;
import com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestSyslogEntry {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value1;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test1()  throws Throwable  {
      Class<?> class0 = Object.class;
      QName qName0 = new QName("c*xug`0l2%");
      // Undeclared exception!
      try {
        SyslogEntry.getSerializer("c*xug`0l2%", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      Class<?> class0 = SyslogEntry.class;
      // Undeclared exception!
      try {
        SyslogEntry.getDeserializer((String) null, (Class) class0, (QName) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value1;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try {
        SyslogEntry.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value1;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test9()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value1;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test11()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value4;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test15()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value1;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test17()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test18()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test19()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test20()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test21()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test22()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }

  @Test
  public void test23()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value1;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test24()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value1;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test25()  throws Throwable  {
      SyslogEntry syslogEntry0 = null;
      try {
        syslogEntry0 = new SyslogEntry();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.SyslogEntry
         */
      }
  }
}
