/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.AlertNode;
import com.sap.managementconsole.soap.axis.sapcontrol.STATECOLOR;
import com.sap.managementconsole.soap.axis.sapcontrol.VISIBLELEVEL;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestAlertNode {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      Class<?> class0 = AlertNode.class;
      QName qName0 = new QName("parent", "parent", "parent");
      // Undeclared exception!
      try {
        AlertNode.getSerializer("parent", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      Class<?> class0 = AlertNode.class;
      QName qName0 = new QName("", "", "");
      // Undeclared exception!
      try {
        AlertNode.getDeserializer("", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try {
        AlertNode.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value3;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test16()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test18()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test19()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test20()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test21()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test22()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test23()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test24()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test25()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test26()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test27()  throws Throwable  {
      AlertNode alertNode0 = null;
      try {
        alertNode0 = new AlertNode();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.AlertNode
         */
      }
  }

  @Test
  public void test28()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value4;
      } catch(NoClassDefFoundError e) {}
  }
}
