/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.J2EEPSTATE;
import java.io.ObjectStreamException;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestJ2EEPSTATE {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      J2EEPSTATE j2EEPSTATE0 = null;
      try {
        j2EEPSTATE0 = new J2EEPSTATE("");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEPSTATE
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Class<?> class0 = J2EEPSTATE.class;
      QName qName0 = new QName("");
      // Undeclared exception!
      try {
        J2EEPSTATE.getDeserializer(")fSc:(n`+g%^A>!H", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEPSTATE
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      J2EEPSTATE j2EEPSTATE0 = null;
      try {
        j2EEPSTATE0 = J2EEPSTATE.value6;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try {
        J2EEPSTATE.fromString("");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEPSTATE
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try {
        J2EEPSTATE.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEPSTATE
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try {
        J2EEPSTATE.fromString("");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEPSTATE
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      Class<?> class0 = J2EEPSTATE.class;
      QName qName0 = new QName("");
      // Undeclared exception!
      try {
        J2EEPSTATE.getSerializer("", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEPSTATE
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try {
        J2EEPSTATE.fromString(";l=~|\"Z9k\n3E");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEPSTATE
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      // Undeclared exception!
      try {
        J2EEPSTATE.fromString("");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEPSTATE
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      J2EEPSTATE j2EEPSTATE0 = null;
      try {
        j2EEPSTATE0 = J2EEPSTATE.value7;
      } catch(NoClassDefFoundError e) {}
  }
}
