/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestJ2EEEJBSession {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession((-12), "_A^L2.MU/G%z$yt:m", (-12), (-12), (-12), "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m", (-12), "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession(0, "Trying to find [", 0, 0, 0, "Trying to find [", "Trying to find [", "Trying to find [", "Trying to find [", 0, "Trying to find [", "Trying to find [", "Trying to find [", "Trying to find [", "Trying to find [");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try {
        J2EEEJBSession.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession(827, "%uJ?JhD+sx* R7e1q-0", 827, 827, 827, "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0", 827, "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession((-12), "_A^L2.MU/G%z$yt:m", (-12), (-12), (-12), "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m", (-12), "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m", "_A^L2.MU/G%z$yt:m");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      Class<?> class0 = J2EEEJBSession.class;
      QName qName0 = new QName("Warning - null logger in onstructor; possible logj misconfiguration.", "Warning - null logger in onstructor; possible logj misconfiguration.", "Warning - null logger in onstructor; possible logj misconfiguration.");
      // Undeclared exception!
      try {
        J2EEEJBSession.getSerializer("Warning - null logger in onstructor; possible logj misconfiguration.", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      Class<?> class0 = J2EEEJBSession.class;
      // Undeclared exception!
      try {
        J2EEEJBSession.getDeserializer((String) null, (Class) class0, (QName) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession(827, "%uJ?JhD+sx* R7e1q-0", 827, 827, 827, "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0", 827, "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0", "%uJ?JhD+sx* R7e1q-0");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession((-7), (String) null, (-7), (-7), (-7), "b", "b", "b", "b", (-7), "b", "b", "b", "b", "b");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test18()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession(0, (String) null, 35, 0, 0, (String) null, (String) null, (String) null, (String) null, 35, (String) null, "_PA^L2.MU/p%z$yt:m", (String) null, "_PA^L2.MU/p%z$yt:m", (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test19()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession(12, "", 12, 12, 12, "", "", "", "", 12, "", "", "", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test20()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession(0, "_PA^L2.MU/p%z$yt:m", 35, 35, 35, "_PA^L2.MU/p%z$yt:m", "_PA^L2.MU/p%z$yt:m", "_PA^L2.MU/p%z$yt:m", "_PA^L2.MU/p%z$yt:m", 35, "_PA^L2.MU/p%z$yt:m", "_PA^L2.MU/p%z$yt:m", "_PA^L2.MU/p%z$yt:m", "_PA^L2.MU/p%z$yt:m", "_PA^L2.MU/p%z$yt:m");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test21()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test22()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test23()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test24()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test25()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession(0, (String) null, 0, 0, 0, (String) null, (String) null, (String) null, (String) null, 35, (String) null, (String) null, (String) null, (String) null, (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test26()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test27()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test28()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test29()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test30()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test31()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }

  @Test
  public void test32()  throws Throwable  {
      J2EEEJBSession j2EEEJBSession0 = null;
      try {
        j2EEEJBSession0 = new J2EEEJBSession(0, "Trying to find [", 0, 0, 0, "Trying to find [", "Trying to find [", "Trying to find [", "Trying to find [", 0, "Trying to find [", "Trying to find [", "Trying to find [", "Trying to find [", "Trying to find [");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EEEJBSession
         */
      }
  }
}
