/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.J2EECache;
import com.sap.managementconsole.soap.axis.sapcontrol.STATECOLOR;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestJ2EECache {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        J2EECache.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache("IX$hbBVpXiAA0(]= ", "IX$hbBVpXiAA0(]= ", "IX$hbBVpXiAA0(]= ", 0L, (-1168L), (-1168L), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "IX$hbBVpXiAA0(]= ", (STATECOLOR) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      Class<?> class0 = STATECOLOR.class;
      QName qName0 = new QName("qoSIcUgo[", "qoSIcUgo[");
      // Undeclared exception!
      try {
        J2EECache.getSerializer("qoSIcUgo[", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      Class<?> class0 = J2EECache.class;
      // Undeclared exception!
      try {
        J2EECache.getDeserializer("5r&uAP", (Class) class0, (QName) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value3;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test17()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value3;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test18()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test19()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test20()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache("V!atYGvu&mz", "o>c\".XHm", "o>c\".XHm", 0L, (long) (-1721), (long) (-1721), (-1721), (-1721), (-1721), (-1721), (-1721), (-1721), (-1721), (-1721), (-1721), (-1721), "o>c\".XHm", (STATECOLOR) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test21()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test22()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test23()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value2;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test24()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test25()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test26()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test27()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test28()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test29()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test30()  throws Throwable  {
      J2EECache j2EECache0 = null;
      try {
        j2EECache0 = new J2EECache();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.J2EECache
         */
      }
  }

  @Test
  public void test31()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value3;
      } catch(NoClassDefFoundError e) {}
  }
}
