/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.Alert;
import com.sap.managementconsole.soap.axis.sapcontrol.STATECOLOR;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestAlert {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Class<?> class0 = QName.class;
      QName qName0 = new QName("bz~?aO*ev9|", "bz~?aO*ev9|", "bz~?aO*ev9|");
      // Undeclared exception!
      try {
        Alert.getDeserializer("bz~?aO*ev9|", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      Class<?> class0 = STATECOLOR.class;
      QName qName0 = new QName("DBbRuRb", "DBbRuRb", "DBbRuRb");
      // Undeclared exception!
      try {
        Alert.getSerializer("DBbRuRb", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try {
        Alert.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value3;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test10()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value2;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test11()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value4;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test12()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test18()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test19()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test20()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test21()  throws Throwable  {
      Alert alert0 = null;
      try {
        alert0 = new Alert();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.Alert
         */
      }
  }

  @Test
  public void test22()  throws Throwable  {
      STATECOLOR sTATECOLOR0 = null;
      try {
        sTATECOLOR0 = STATECOLOR.value3;
      } catch(NoClassDefFoundError e) {}
  }
}
