/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestInstanceVersionInfo {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      InstanceVersionInfo instanceVersionInfo0 = null;
      try {
        instanceVersionInfo0 = new InstanceVersionInfo();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Class<?> class0 = InstanceVersionInfo.class;
      QName qName0 = new QName("k_HvB7>leIlzk", "k_HvB7>leIlzk", "k_HvB7>leIlzk");
      // Undeclared exception!
      try {
        InstanceVersionInfo.getSerializer("k_HvB7>leIlzk", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      InstanceVersionInfo instanceVersionInfo0 = null;
      try {
        instanceVersionInfo0 = new InstanceVersionInfo("", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      InstanceVersionInfo instanceVersionInfo0 = null;
      try {
        instanceVersionInfo0 = new InstanceVersionInfo();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try {
        InstanceVersionInfo.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      Class<?> class0 = Object.class;
      QName qName0 = new QName("Ed:r/3Lg .Bgc");
      // Undeclared exception!
      try {
        InstanceVersionInfo.getDeserializer("m", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      InstanceVersionInfo instanceVersionInfo0 = null;
      try {
        instanceVersionInfo0 = new InstanceVersionInfo();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      InstanceVersionInfo instanceVersionInfo0 = null;
      try {
        instanceVersionInfo0 = new InstanceVersionInfo("Ed:r/3Lg .Bgc", "Ed:r/3Lg .Bgc", "Ed:r/3Lg .Bgc");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      InstanceVersionInfo instanceVersionInfo0 = null;
      try {
        instanceVersionInfo0 = new InstanceVersionInfo();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      InstanceVersionInfo instanceVersionInfo0 = null;
      try {
        instanceVersionInfo0 = new InstanceVersionInfo();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      InstanceVersionInfo instanceVersionInfo0 = null;
      try {
        instanceVersionInfo0 = new InstanceVersionInfo();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      InstanceVersionInfo instanceVersionInfo0 = null;
      try {
        instanceVersionInfo0 = new InstanceVersionInfo("Ed:r/3Lg .Bgc", "Ed:r/3Lg .Bgc", "Ed:r/3Lg .Bgc");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      InstanceVersionInfo instanceVersionInfo0 = null;
      try {
        instanceVersionInfo0 = new InstanceVersionInfo("Ed:r/3Lg .Bgc", "Ed:r/3Lg .Bgc", "Ed:r/3Lg .Bgc");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      InstanceVersionInfo instanceVersionInfo0 = null;
      try {
        instanceVersionInfo0 = new InstanceVersionInfo("Ed:r/3Lg .Bgc", "Ed:r/3Lg .Bgc", "Ed:r/3Lg .Bgc");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.InstanceVersionInfo
         */
      }
  }
}
