/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestTaskHandlerQueue {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue("8I!", 1721, 1721, 1721, 1721, 10);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue("8I!", 1721, 1721, 1721, 1721, 10);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue("8I!", 1721, 1721, 1721, 1721, 10);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue("Pb^uy!d`+.", 10042, 20012, 20012, 20012, 20012);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try {
        TaskHandlerQueue.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue("Pb^uy!d`+.", 10042, 20012, 20012, 20012, 20012);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue((String) null, 812, 812, 812, 812, 812);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      Class<?> class0 = Class.class;
      QName qName0 = new QName("8I!", "8I!");
      // Undeclared exception!
      try {
        TaskHandlerQueue.getDeserializer("8I!", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      Class<?> class0 = Class.class;
      QName qName0 = new QName("8I!", "8I!");
      // Undeclared exception!
      try {
        TaskHandlerQueue.getSerializer("8I!", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue((String) null, 812, 812, 812, 812, 812);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue((String) null, 812, 812, 812, 812, 812);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue("8I!", 1721, 1721, 1721, 1721, 10);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue("Pb^uy!d`+.", 10042, 20012, 20012, 20012, 20012);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      TaskHandlerQueue taskHandlerQueue0 = null;
      try {
        taskHandlerQueue0 = new TaskHandlerQueue();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.TaskHandlerQueue
         */
      }
  }
}
