/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.ICMThread;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestICMThread {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread(" from\"", " from\"", 1L, " from\"", " from\"");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try {
        ICMThread.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread("vF", "vF", (-14L), "vF", "vF");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      Class<?> class0 = ICMThread.class;
      QName qName0 = QName.valueOf("vF");
      // Undeclared exception!
      try {
        ICMThread.getDeserializer("vF", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread("vF", "vF", (-14L), "vF", "vF");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      Class<?> class0 = Class.class;
      QName qName0 = QName.valueOf("M!5&Qu");
      // Undeclared exception!
      try {
        ICMThread.getSerializer("M!5&Qu", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread(" from\"", " from\"", 1L, " from\"", " from\"");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread("", "", 7L, "", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread((String) null, "M!5&Qu", 1073741824L, (String) null, (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread("L", "L", (-1079L), "L", "L");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread("ZD+qEY;N1@`R:", "ZD+qEY;N1@`R:", (-1010L), "ZD+qEY;N1@`R:", "ZD+qEY;N1@`R:");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test18()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test19()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread(" from\"", " from\"", 1L, " from\"", " from\"");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }

  @Test
  public void test20()  throws Throwable  {
      ICMThread iCMThread0 = null;
      try {
        iCMThread0 = new ICMThread();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.sapcontrol.ICMThread
         */
      }
  }
}
