/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.lavalamp.device.impl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sf.lavalamp.device.impl.TellStick;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestTellStick {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TellStick tellStick0 = new TellStick();
      Runtime runtime0 = Runtime.getRuntime();
      tellStick0.setRuntime(runtime0);
      assertEquals("TellStick null ", tellStick0.toString());
  }

  @Test
  public void test1()  throws Throwable  {
      TellStick tellStick0 = new TellStick();
      tellStick0.init();
      assertEquals("TellStick null ", tellStick0.toString());
  }

  @Test
  public void test2()  throws Throwable  {
      TellStick tellStick0 = new TellStick();
      // Undeclared exception!
      try {
        tellStick0.turnOff();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      TellStick tellStick0 = new TellStick();
      // Undeclared exception!
      try {
        tellStick0.turnOn();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test4()  throws Throwable  {
      TellStick tellStick0 = new TellStick();
      // Undeclared exception!
      try {
        tellStick0.exec("");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
