/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.lavalamp.device.impl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sf.lavalamp.device.impl.TellStickJni;
import net.sf.lavalamp.device.impl.TellStickLibrary;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestTellStickJni {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TellStickJni tellStickJni0 = new TellStickJni();
      tellStickJni0.setLibrary((TellStickLibrary) null);
      assertEquals("device null", tellStickJni0.toString());
  }

  @Test
  public void test1()  throws Throwable  {
      TellStickJni tellStickJni0 = new TellStickJni();
      // Undeclared exception!
      try {
        tellStickJni0.init();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sun.jna.Native
         */
      }
  }
}
