/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.lavalamp.application;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sf.lavalamp.application.BuildStatusServlet;
import net.sf.lavalamp.device.DeviceController;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class BuildStatusServletEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      BuildStatusServlet buildStatusServlet0 = new BuildStatusServlet((DeviceController) null);
      assertEquals("", buildStatusServlet0.getServletInfo());
  }
}
