/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.engine.services.dc.wsgate;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.engine.services.dc.wsgate.Application;
import com.sap.engine.services.dc.wsgate.ArchiveFile;
import com.sap.engine.services.dc.wsgate.DeployFault;
import com.sap.engine.services.dc.wsgate.DeployWSPortTypeBindingStub;
import com.sap.engine.services.dc.wsgate.DeployWSPortTypeProxy;
import com.sap.engine.services.dc.wsgate.Option;
import java.rmi.RemoteException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import javax.xml.rpc.JAXRPCException;
import org.apache.axis.AxisFault;
import org.evosuite.Properties.SandboxMode;
import org.evosuite.sandbox.Sandbox;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class DeployWSPortTypeProxyEvoSuiteTest {

  private static ExecutorService executor; 

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
    org.evosuite.Properties.SANDBOX_MODE = SandboxMode.RECOMMENDED; 
    Sandbox.initializeSecurityManagerForSUT(); 
    executor = Executors.newCachedThreadPool(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    executor.shutdownNow(); 
    Sandbox.resetDefaultSecurityManager(); 
  } 

  @Before 
  public void initTestCase(){ 
    Sandbox.goingToExecuteSUTCode(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    Sandbox.doneWithExecutingSUTCode(); 
  } 


  @Test
  public void test0()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
          DeployWSPortTypeProxy deployWSPortTypeProxy0 = new DeployWSPortTypeProxy();
          deployWSPortTypeProxy0.getEndpoint();
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test1()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
          DeployWSPortTypeProxy deployWSPortTypeProxy0 = null;
          try {
            deployWSPortTypeProxy0 = new DeployWSPortTypeProxy("cvc-maxInclusive-valid");
            fail("Expecting exception: JAXRPCException");
          } catch(JAXRPCException e) {
            /*
             * no protocol: cvc-maxInclusive-valid
             */
          }
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test2()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
          DeployWSPortTypeProxy deployWSPortTypeProxy0 = new DeployWSPortTypeProxy();
          deployWSPortTypeProxy0.setEndpoint("http://10.66.212.71:50000/DeployWSService/DeployWS");
          assertEquals("http://10.66.212.71:50000/DeployWSService/DeployWS", deployWSPortTypeProxy0.getEndpoint());
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test3()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
          DeployWSPortTypeProxy deployWSPortTypeProxy0 = new DeployWSPortTypeProxy();
          DeployWSPortTypeBindingStub deployWSPortTypeBindingStub0 = (DeployWSPortTypeBindingStub)deployWSPortTypeProxy0.getDeployWSPortType();
          assertNull(deployWSPortTypeBindingStub0.getPassword());
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test4()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
        try {
          DeployWSPortTypeProxy deployWSPortTypeProxy0 = new DeployWSPortTypeProxy();
          Application[] applicationArray0 = new Application[18];
          Option[] optionArray0 = new Option[8];
          try {
            deployWSPortTypeProxy0.start(applicationArray0, optionArray0);
            fail("Expecting exception: AxisFault");
          } catch(AxisFault e) {
            /*
             * ; nested exception is: 
             * \tjava.lang.SecurityException: Security manager blocks (java.net.SocketPermission 10.66.212.71:50000 connect,resolve)
             * java.lang.Thread.getStackTrace(Thread.java:1479)
             * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
             * java.lang.SecurityManager.checkConnect(SecurityManager.java:1034)
             * java.net.Socket.connect(Socket.java:524)
             * sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:153)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:120)
             * org.apache.axis.transport.http.HTTPSender.getSocket(HTTPSender.java:191)
             * org.apache.axis.transport.http.HTTPSender.writeToSocket(HTTPSender.java:404)
             * org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:138)
             * org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
             * org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
             * org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
             * org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
             * org.apache.axis.client.Call.invokeEngine(Call.java:2784)
             * org.apache.axis.client.Call.invoke(Call.java:2767)
             * org.apache.axis.client.Call.invoke(Call.java:2443)
             * org.apache.axis.client.Call.invoke(Call.java:2366)
             * org.apache.axis.client.Call.invoke(Call.java:1812)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeBindingStub.start(DeployWSPortTypeBindingStub.java:421)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeProxy.start(DeployWSPortTypeProxy.java:60)
             * sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             * sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.evosuite.testcase.MethodStatement$1.execute(MethodStatement.java:262)
             * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
             * org.evosuite.testcase.MethodStatement.execute(MethodStatement.java:217)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:44)
             * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
             * java.util.concurrent.FutureTask.run(FutureTask.java:138)
             * java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
             * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
             * java.lang.Thread.run(Thread.java:662)
             */
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test5()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
        try {
          DeployWSPortTypeProxy deployWSPortTypeProxy0 = new DeployWSPortTypeProxy();
          Application[] applicationArray0 = new Application[10];
          Option[] optionArray0 = new Option[7];
          try {
            deployWSPortTypeProxy0.stop(applicationArray0, optionArray0);
            fail("Expecting exception: AxisFault");
          } catch(AxisFault e) {
            /*
             * ; nested exception is: 
             * \tjava.lang.SecurityException: Security manager blocks (java.net.SocketPermission 10.66.212.71:50000 connect,resolve)
             * java.lang.Thread.getStackTrace(Thread.java:1479)
             * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
             * java.lang.SecurityManager.checkConnect(SecurityManager.java:1034)
             * java.net.Socket.connect(Socket.java:524)
             * sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:153)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:120)
             * org.apache.axis.transport.http.HTTPSender.getSocket(HTTPSender.java:191)
             * org.apache.axis.transport.http.HTTPSender.writeToSocket(HTTPSender.java:404)
             * org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:138)
             * org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
             * org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
             * org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
             * org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
             * org.apache.axis.client.Call.invokeEngine(Call.java:2784)
             * org.apache.axis.client.Call.invoke(Call.java:2767)
             * org.apache.axis.client.Call.invoke(Call.java:2443)
             * org.apache.axis.client.Call.invoke(Call.java:2366)
             * org.apache.axis.client.Call.invoke(Call.java:1812)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeBindingStub.stop(DeployWSPortTypeBindingStub.java:463)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeProxy.stop(DeployWSPortTypeProxy.java:66)
             * sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             * sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.evosuite.testcase.MethodStatement$1.execute(MethodStatement.java:262)
             * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
             * org.evosuite.testcase.MethodStatement.execute(MethodStatement.java:217)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:44)
             * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
             * java.util.concurrent.FutureTask.run(FutureTask.java:138)
             * java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
             * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
             * java.lang.Thread.run(Thread.java:662)
             */
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test6()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
        try {
          DeployWSPortTypeProxy deployWSPortTypeProxy0 = new DeployWSPortTypeProxy();
          try {
            deployWSPortTypeProxy0.getVersion();
            fail("Expecting exception: AxisFault");
          } catch(AxisFault e) {
            /*
             * ; nested exception is: 
             * \tjava.lang.SecurityException: Security manager blocks (java.net.SocketPermission 10.66.212.71:50000 connect,resolve)
             * java.lang.Thread.getStackTrace(Thread.java:1479)
             * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
             * java.lang.SecurityManager.checkConnect(SecurityManager.java:1034)
             * java.net.Socket.connect(Socket.java:524)
             * sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:153)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:120)
             * org.apache.axis.transport.http.HTTPSender.getSocket(HTTPSender.java:191)
             * org.apache.axis.transport.http.HTTPSender.writeToSocket(HTTPSender.java:404)
             * org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:138)
             * org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
             * org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
             * org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
             * org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
             * org.apache.axis.client.Call.invokeEngine(Call.java:2784)
             * org.apache.axis.client.Call.invoke(Call.java:2767)
             * org.apache.axis.client.Call.invoke(Call.java:2443)
             * org.apache.axis.client.Call.invoke(Call.java:2366)
             * org.apache.axis.client.Call.invoke(Call.java:1812)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeBindingStub.getVersion(DeployWSPortTypeBindingStub.java:505)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeProxy.getVersion(DeployWSPortTypeProxy.java:72)
             * sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             * sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.evosuite.testcase.MethodStatement$1.execute(MethodStatement.java:262)
             * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
             * org.evosuite.testcase.MethodStatement.execute(MethodStatement.java:217)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:44)
             * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
             * java.util.concurrent.FutureTask.run(FutureTask.java:138)
             * java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
             * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
             * java.lang.Thread.run(Thread.java:662)
             */
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test7()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
        try {
          DeployWSPortTypeProxy deployWSPortTypeProxy0 = new DeployWSPortTypeProxy();
          ArchiveFile[] archiveFileArray0 = new ArchiveFile[4];
          Option[] optionArray0 = new Option[2];
          try {
            deployWSPortTypeProxy0.deploy(archiveFileArray0, optionArray0);
            fail("Expecting exception: AxisFault");
          } catch(AxisFault e) {
            /*
             * ; nested exception is: 
             * \tjava.lang.SecurityException: Security manager blocks (java.net.SocketPermission 10.66.212.71:50000 connect,resolve)
             * java.lang.Thread.getStackTrace(Thread.java:1479)
             * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
             * java.lang.SecurityManager.checkConnect(SecurityManager.java:1034)
             * java.net.Socket.connect(Socket.java:524)
             * sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:153)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:120)
             * org.apache.axis.transport.http.HTTPSender.getSocket(HTTPSender.java:191)
             * org.apache.axis.transport.http.HTTPSender.writeToSocket(HTTPSender.java:404)
             * org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:138)
             * org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
             * org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
             * org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
             * org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
             * org.apache.axis.client.Call.invokeEngine(Call.java:2784)
             * org.apache.axis.client.Call.invoke(Call.java:2767)
             * org.apache.axis.client.Call.invoke(Call.java:2443)
             * org.apache.axis.client.Call.invoke(Call.java:2366)
             * org.apache.axis.client.Call.invoke(Call.java:1812)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeBindingStub.deploy(DeployWSPortTypeBindingStub.java:539)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeProxy.deploy(DeployWSPortTypeProxy.java:78)
             * sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             * sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.evosuite.testcase.MethodStatement$1.execute(MethodStatement.java:262)
             * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
             * org.evosuite.testcase.MethodStatement.execute(MethodStatement.java:217)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:44)
             * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
             * java.util.concurrent.FutureTask.run(FutureTask.java:138)
             * java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
             * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
             * java.lang.Thread.run(Thread.java:662)
             */
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test8()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
        try {
          DeployWSPortTypeProxy deployWSPortTypeProxy0 = new DeployWSPortTypeProxy();
          Option[] optionArray0 = new Option[24];
          try {
            deployWSPortTypeProxy0.getApplications(optionArray0);
            fail("Expecting exception: AxisFault");
          } catch(AxisFault e) {
            /*
             * ; nested exception is: 
             * \tjava.lang.SecurityException: Security manager blocks (java.net.SocketPermission 10.66.212.71:50000 connect,resolve)
             * java.lang.Thread.getStackTrace(Thread.java:1479)
             * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
             * java.lang.SecurityManager.checkConnect(SecurityManager.java:1034)
             * java.net.Socket.connect(Socket.java:524)
             * sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:153)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:120)
             * org.apache.axis.transport.http.HTTPSender.getSocket(HTTPSender.java:191)
             * org.apache.axis.transport.http.HTTPSender.writeToSocket(HTTPSender.java:404)
             * org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:138)
             * org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
             * org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
             * org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
             * org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
             * org.apache.axis.client.Call.invokeEngine(Call.java:2784)
             * org.apache.axis.client.Call.invoke(Call.java:2767)
             * org.apache.axis.client.Call.invoke(Call.java:2443)
             * org.apache.axis.client.Call.invoke(Call.java:2366)
             * org.apache.axis.client.Call.invoke(Call.java:1812)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeBindingStub.getApplications(DeployWSPortTypeBindingStub.java:581)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeProxy.getApplications(DeployWSPortTypeProxy.java:84)
             * sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             * sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.evosuite.testcase.MethodStatement$1.execute(MethodStatement.java:262)
             * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
             * org.evosuite.testcase.MethodStatement.execute(MethodStatement.java:217)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:44)
             * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
             * java.util.concurrent.FutureTask.run(FutureTask.java:138)
             * java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
             * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
             * java.lang.Thread.run(Thread.java:662)
             */
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test9()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
        try {
          DeployWSPortTypeProxy deployWSPortTypeProxy0 = new DeployWSPortTypeProxy();
          Application[] applicationArray0 = new Application[2];
          Option[] optionArray0 = new Option[1];
          try {
            deployWSPortTypeProxy0.undeploy(applicationArray0, optionArray0);
            fail("Expecting exception: AxisFault");
          } catch(AxisFault e) {
            /*
             * ; nested exception is: 
             * \tjava.lang.SecurityException: Security manager blocks (java.net.SocketPermission 10.66.212.71:50000 connect,resolve)
             * java.lang.Thread.getStackTrace(Thread.java:1479)
             * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
             * java.lang.SecurityManager.checkConnect(SecurityManager.java:1034)
             * java.net.Socket.connect(Socket.java:524)
             * sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:153)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:120)
             * org.apache.axis.transport.http.HTTPSender.getSocket(HTTPSender.java:191)
             * org.apache.axis.transport.http.HTTPSender.writeToSocket(HTTPSender.java:404)
             * org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:138)
             * org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
             * org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
             * org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
             * org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
             * org.apache.axis.client.Call.invokeEngine(Call.java:2784)
             * org.apache.axis.client.Call.invoke(Call.java:2767)
             * org.apache.axis.client.Call.invoke(Call.java:2443)
             * org.apache.axis.client.Call.invoke(Call.java:2366)
             * org.apache.axis.client.Call.invoke(Call.java:1812)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeBindingStub.undeploy(DeployWSPortTypeBindingStub.java:623)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeProxy.undeploy(DeployWSPortTypeProxy.java:90)
             * sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             * sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.evosuite.testcase.MethodStatement$1.execute(MethodStatement.java:262)
             * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
             * org.evosuite.testcase.MethodStatement.execute(MethodStatement.java:217)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:44)
             * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
             * java.util.concurrent.FutureTask.run(FutureTask.java:138)
             * java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
             * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
             * java.lang.Thread.run(Thread.java:662)
             */
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test10()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
        try {
          DeployWSPortTypeProxy deployWSPortTypeProxy0 = new DeployWSPortTypeProxy();
          Option[] optionArray0 = new Option[1];
          String[] stringArray0 = new String[2];
          try {
            deployWSPortTypeProxy0.deployLocal(stringArray0, optionArray0);
            fail("Expecting exception: AxisFault");
          } catch(AxisFault e) {
            /*
             * ; nested exception is: 
             * \tjava.lang.SecurityException: Security manager blocks (java.net.SocketPermission 10.66.212.71:50000 connect,resolve)
             * java.lang.Thread.getStackTrace(Thread.java:1479)
             * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
             * java.lang.SecurityManager.checkConnect(SecurityManager.java:1034)
             * java.net.Socket.connect(Socket.java:524)
             * sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:153)
             * org.apache.axis.components.net.DefaultSocketFactory.create(DefaultSocketFactory.java:120)
             * org.apache.axis.transport.http.HTTPSender.getSocket(HTTPSender.java:191)
             * org.apache.axis.transport.http.HTTPSender.writeToSocket(HTTPSender.java:404)
             * org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:138)
             * org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
             * org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
             * org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
             * org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
             * org.apache.axis.client.Call.invokeEngine(Call.java:2784)
             * org.apache.axis.client.Call.invoke(Call.java:2767)
             * org.apache.axis.client.Call.invoke(Call.java:2443)
             * org.apache.axis.client.Call.invoke(Call.java:2366)
             * org.apache.axis.client.Call.invoke(Call.java:1812)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeBindingStub.deployLocal(DeployWSPortTypeBindingStub.java:665)
             * com.sap.engine.services.dc.wsgate.DeployWSPortTypeProxy.deployLocal(DeployWSPortTypeProxy.java:96)
             * sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             * sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
             * java.lang.reflect.Method.invoke(Method.java:597)
             * org.evosuite.testcase.MethodStatement$1.execute(MethodStatement.java:262)
             * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
             * org.evosuite.testcase.MethodStatement.execute(MethodStatement.java:217)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:44)
             * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
             * java.util.concurrent.FutureTask.run(FutureTask.java:138)
             * java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
             * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
             * java.lang.Thread.run(Thread.java:662)
             */
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }
}
