/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.engine.services.dc.wsgate;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.engine.services.dc.wsgate.Option;
import javax.xml.namespace.QName;
import org.apache.axis.description.TypeDesc;
import org.apache.axis.encoding.ser.BeanDeserializer;
import org.apache.axis.encoding.ser.BeanSerializer;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class OptionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      QName qName0 = new QName("'!(g.>qdn(#");
      Class<?> class0 = Class.class;
      BeanSerializer beanSerializer0 = (BeanSerializer)Option.getSerializer("'!(g.>qdn(#", (Class) class0, qName0);
      assertEquals("Axis SAX Mechanism", beanSerializer0.getMechanismType());
  }

  @Test
  public void test1()  throws Throwable  {
      Option option0 = new Option();
      option0.setValue((Object) option0);
      int int0 = option0.hashCode();
      assertEquals(1, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      Option option0 = new Option();
      Object object0 = new Object();
      Option option1 = new Option(object0, (Object) option0);
      boolean boolean0 = option0.equals((Object) option1);
      assertEquals(false, boolean0);
  }

  @Test
  public void test3()  throws Throwable  {
      Option option0 = new Option();
      Object object0 = new Object();
      option0.setKey(object0);
  }

  @Test
  public void test4()  throws Throwable  {
      TypeDesc typeDesc0 = Option.getTypeDesc();
      assertEquals(false, typeDesc0.hasAttributes());
  }

  @Test
  public void test5()  throws Throwable  {
      Option option0 = new Option();
      int int0 = option0.hashCode();
      assertEquals(1, int0);
  }

  @Test
  public void test6()  throws Throwable  {
      QName qName0 = new QName("");
      Class<?> class0 = Option.class;
      BeanDeserializer beanDeserializer0 = (BeanDeserializer)Option.getDeserializer("", (Class) class0, qName0);
      assertEquals("Axis SAX Mechanism", beanDeserializer0.getMechanismType());
  }

  @Test
  public void test7()  throws Throwable  {
      Option option0 = new Option();
      Option option1 = new Option((Object) "", (Object) option0);
      Option option2 = new Option((Object) "", (Object) "[ENV] No cnfigurati'n defined for ite ");
      boolean boolean0 = option1.equals((Object) option2);
      assertEquals(false, boolean0);
      assertFalse(option2.equals(option0));
      assertFalse(option0.equals(option1));
  }

  @Test
  public void test8()  throws Throwable  {
      Option option0 = new Option((Object) "", (Object) "");
      Option option1 = new Option();
      boolean boolean0 = option0.equals((Object) option1);
      assertEquals(false, boolean0);
      assertFalse(option1.equals(option0));
  }

  @Test
  public void test9()  throws Throwable  {
      Option option0 = new Option();
      Option option1 = new Option();
      assertTrue(option1.equals(option0));
      
      option0.setValue((Object) option0);
      boolean boolean0 = option1.equals((Object) option0);
      assertFalse(option1.equals(option0));
      assertEquals(false, boolean0);
  }

  @Test
  public void test10()  throws Throwable  {
      Option option0 = new Option();
      Option option1 = new Option((Object) "", (Object) option0);
      Option option2 = new Option((Object) "", (Object) "");
      assertFalse(option2.equals(option1));
      
      Option option3 = new Option();
      option2.setValue((Object) option3);
      boolean boolean0 = option1.equals((Object) option2);
      assertTrue(option2.equals(option1));
      assertEquals(true, boolean0);
  }

  @Test
  public void test11()  throws Throwable  {
      Option option0 = new Option((Object) "", (Object) "");
      int int0 = option0.hashCode();
      assertEquals(1, int0);
  }
}
