/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.engine.services.dc.wsgate;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.engine.services.dc.wsgate.ArchiveFile;
import com.sap.engine.services.dc.wsgate.Deploy;
import com.sap.engine.services.dc.wsgate.Option;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDeploy {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Deploy deploy0 = null;
      try {
        deploy0 = new Deploy();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Deploy deploy0 = null;
      try {
        deploy0 = new Deploy();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      Class<?> class0 = Deploy.class;
      QName qName0 = new QName("java.`yxt.dir", "java.`yxt.dir", "java.`yxt.dir");
      // Undeclared exception!
      try {
        Deploy.getSerializer("java.`yxt.dir", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      ArchiveFile[] archiveFileArray0 = new ArchiveFile[2];
      Option[] optionArray0 = new Option[3];
      Option option0 = null;
      try {
        option0 = new Option();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Option
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      Deploy deploy0 = null;
      try {
        deploy0 = new Deploy();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      Deploy deploy0 = null;
      try {
        deploy0 = new Deploy();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      QName qName0 = new QName("T", "T");
      Class<?> class0 = QName.class;
      // Undeclared exception!
      try {
        Deploy.getDeserializer("T", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try {
        Deploy.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      Deploy deploy0 = null;
      try {
        deploy0 = new Deploy();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      ArchiveFile[] archiveFileArray0 = new ArchiveFile[5];
      Option[] optionArray0 = new Option[9];
      Deploy deploy0 = null;
      try {
        deploy0 = new Deploy(archiveFileArray0, optionArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      ArchiveFile[] archiveFileArray0 = new ArchiveFile[5];
      Option[] optionArray0 = new Option[9];
      Deploy deploy0 = null;
      try {
        deploy0 = new Deploy(archiveFileArray0, optionArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      Deploy deploy0 = null;
      try {
        deploy0 = new Deploy();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      ArchiveFile[] archiveFileArray0 = new ArchiveFile[5];
      Option[] optionArray0 = new Option[9];
      Deploy deploy0 = null;
      try {
        deploy0 = new Deploy(archiveFileArray0, optionArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      Option[] optionArray0 = new Option[11];
      Deploy deploy0 = null;
      try {
        deploy0 = new Deploy();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      Deploy deploy0 = null;
      try {
        deploy0 = new Deploy();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      Deploy deploy0 = null;
      try {
        deploy0 = new Deploy();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Deploy
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      ArchiveFile[] archiveFileArray0 = new ArchiveFile[2];
      ArchiveFile archiveFile0 = null;
      try {
        archiveFile0 = new ArchiveFile();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.ArchiveFile
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      ArchiveFile[] archiveFileArray0 = new ArchiveFile[2];
      Option[] optionArray0 = new Option[3];
      Option option0 = null;
      try {
        option0 = new Option();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Option
         */
      }
  }
}
