/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.engine.services.dc.wsgate;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.engine.services.dc.wsgate.Application;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestApplication {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application(")t-lmt=", ")t-lmt=", ")t-lmt=", ")t-lmt=", ")t-lmt=", ")t-lmt=");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application("", "", "", "", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try {
        Application.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      Class<?> class0 = Class.class;
      QName qName0 = QName.valueOf("#,(ZOu#[+18");
      // Undeclared exception!
      try {
        Application.getDeserializer("#,(ZOu#[+18", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      Class<?> class0 = QName.class;
      QName qName0 = QName.valueOf("] Mannot be instantiated due to access restrictions");
      // Undeclared exception!
      try {
        Application.getSerializer((String) null, (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application("", "", "", "", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application((String) null, (String) null, (String) null, (String) null, (String) null, (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application("8**", "D41d9>FWpb", "8**", "8**", "8**", "8**");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test18()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test19()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test20()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application((String) null, (String) null, (String) null, (String) null, (String) null, (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test21()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application("#,(ZOu#[+18", "#,(ZOu#[+18", "#,(ZOu#[+18", "#,(ZOu#[+18", "#,(ZOu#[+18", "#,(ZOu#[+18");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test22()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application("", "", "", "", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }

  @Test
  public void test23()  throws Throwable  {
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }
}
