/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.engine.services.dc.wsgate;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.engine.services.dc.wsgate.GetVersion;
import javax.xml.namespace.QName;
import org.apache.axis.description.TypeDesc;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestGetVersion {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Class<?> class0 = QName.class;
      // Undeclared exception!
      try {
        GetVersion.getSerializer("@7!fh`eJCdEK^J?2!", (Class) class0, (QName) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.GetVersion
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Class<?> class0 = QName.class;
      // Undeclared exception!
      try {
        GetVersion.getDeserializer("@7!fh`eJCdEK^J?2!", (Class) class0, (QName) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.GetVersion
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      GetVersion getVersion0 = null;
      try {
        getVersion0 = new GetVersion();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.GetVersion
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      GetVersion getVersion0 = null;
      try {
        getVersion0 = new GetVersion();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.GetVersion
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      GetVersion getVersion0 = null;
      try {
        getVersion0 = new GetVersion();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.GetVersion
         */
      }
  }
}
