/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.engine.services.dc.wsgate;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.engine.services.dc.wsgate.DeployLocal;
import com.sap.engine.services.dc.wsgate.Option;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDeployLocal {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Class<?> class0 = Option.class;
      // Undeclared exception!
      try {
        DeployLocal.getSerializer((String) null, (Class) class0, (QName) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[9];
      Option[] optionArray0 = new Option[5];
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal(stringArray0, optionArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      Class<?> class0 = Option.class;
      // Undeclared exception!
      try {
        DeployLocal.getDeserializer("log4j.rootLogger", (Class) class0, (QName) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[9];
      Option[] optionArray0 = new Option[5];
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal(stringArray0, optionArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      // Undeclared exception!
      try {
        DeployLocal.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      Option[] optionArray0 = new Option[16];
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal((String[]) null, optionArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      String[] stringArray0 = new String[9];
      Option[] optionArray0 = new Option[5];
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal(stringArray0, optionArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[8] = "N-~V,/=?rtd,zM[E[";
      Option[] optionArray0 = new Option[5];
      DeployLocal deployLocal0 = null;
      try {
        deployLocal0 = new DeployLocal(stringArray0, optionArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployLocal
         */
      }
  }
}
