/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.engine.services.dc.wsgate;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.engine.services.dc.wsgate.Application;
import com.sap.engine.services.dc.wsgate.DeployResult;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDeployResult {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DeployResult deployResult0 = null;
      try {
        deployResult0 = new DeployResult();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Application[] applicationArray0 = new Application[2];
      DeployResult deployResult0 = null;
      try {
        deployResult0 = new DeployResult(applicationArray0, "ICJa~0<I9T>h!;$swJ", "ICJa~0<I9T>h!;$swJ");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      Class<?> class0 = Class.class;
      QName qName0 = new QName("");
      // Undeclared exception!
      try {
        DeployResult.getDeserializer("", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try {
        DeployResult.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      Class<?> class0 = Class.class;
      QName qName0 = new QName("");
      // Undeclared exception!
      try {
        DeployResult.getSerializer("", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      Application[] applicationArray0 = new Application[2];
      DeployResult deployResult0 = null;
      try {
        deployResult0 = new DeployResult(applicationArray0, "ICJa~0<I9T>h!;$swJ", "ICJa~0<I9T>h!;$swJ");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      Application[] applicationArray0 = new Application[2];
      DeployResult deployResult0 = null;
      try {
        deployResult0 = new DeployResult(applicationArray0, "ICJa~0<I9T>h!;$swJ", "ICJa~0<I9T>h!;$swJ");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      DeployResult deployResult0 = null;
      try {
        deployResult0 = new DeployResult();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      Application[] applicationArray0 = new Application[6];
      DeployResult deployResult0 = null;
      try {
        deployResult0 = new DeployResult(applicationArray0, "?B", "?B");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      DeployResult deployResult0 = null;
      try {
        deployResult0 = new DeployResult();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      DeployResult deployResult0 = null;
      try {
        deployResult0 = new DeployResult();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      DeployResult deployResult0 = null;
      try {
        deployResult0 = new DeployResult();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      DeployResult deployResult0 = null;
      try {
        deployResult0 = new DeployResult();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      DeployResult deployResult0 = null;
      try {
        deployResult0 = new DeployResult();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      DeployResult deployResult0 = null;
      try {
        deployResult0 = new DeployResult();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      DeployResult deployResult0 = null;
      try {
        deployResult0 = new DeployResult();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.DeployResult
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      Application[] applicationArray0 = new Application[6];
      Application application0 = null;
      try {
        application0 = new Application();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.engine.services.dc.wsgate.Application
         */
      }
  }
}
