/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.core;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.core.Credentials;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestCredentials {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Credentials credentials0 = new Credentials("", "");
      String string0 = credentials0.getPassword();
      assertEquals("", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      Credentials credentials0 = new Credentials("", "");
      String string0 = credentials0.getUser();
      assertEquals("", string0);
  }
}
