/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.lavalamp.site;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sf.lavalamp.site.SiteProperties;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestSiteProperties {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SiteProperties siteProperties0 = new SiteProperties();
      String string0 = siteProperties0.getGetterClass();
      assertEquals("net.sf.lavalamp.site.UrlGetter", string0);
      assertNotNull(string0);
  }

  @Test
  public void test1()  throws Throwable  {
      SiteProperties siteProperties0 = new SiteProperties();
      siteProperties0.setClassName("");
      assertEquals("net.sf.lavalamp.site.UrlGetter", siteProperties0.getGetterClass());
      assertEquals("\n\t\t\tserver=, url=null getter=net.sf.lavalamp.site.UrlGetter", siteProperties0.toString());
  }

  @Test
  public void test2()  throws Throwable  {
      SiteProperties siteProperties0 = new SiteProperties();
      siteProperties0.setGetterClass("oV!J)(q?&D~-~q");
      assertNull(siteProperties0.getClassName());
  }

  @Test
  public void test3()  throws Throwable  {
      SiteProperties siteProperties0 = new SiteProperties();
      siteProperties0.getClassName();
      assertEquals("net.sf.lavalamp.site.UrlGetter", siteProperties0.getGetterClass());
      assertEquals("\n\t\t\tserver=null, url=null getter=net.sf.lavalamp.site.UrlGetter", siteProperties0.toString());
  }

  @Test
  public void test4()  throws Throwable  {
      SiteProperties siteProperties0 = new SiteProperties();
      siteProperties0.getUrl();
      assertEquals("\n\t\t\tserver=null, url=null getter=net.sf.lavalamp.site.UrlGetter", siteProperties0.toString());
      assertEquals("net.sf.lavalamp.site.UrlGetter", siteProperties0.getGetterClass());
  }

  @Test
  public void test5()  throws Throwable  {
      SiteProperties siteProperties0 = new SiteProperties();
      String string0 = siteProperties0.toString();
      assertNotNull(string0);
      assertEquals("\n\t\t\tserver=null, url=null getter=net.sf.lavalamp.site.UrlGetter", string0);
  }

  @Test
  public void test6()  throws Throwable  {
      SiteProperties siteProperties0 = new SiteProperties();
      siteProperties0.setUrl("");
      assertEquals("\n\t\t\tserver=null, url= getter=net.sf.lavalamp.site.UrlGetter", siteProperties0.toString());
      assertEquals("net.sf.lavalamp.site.UrlGetter", siteProperties0.getGetterClass());
  }
}
