/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.lavalamp.site;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sf.lavalamp.site.DummyRestGetter;
import org.apache.commons.httpclient.UsernamePasswordCredentials;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestAbstractGetter {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DummyRestGetter dummyRestGetter0 = new DummyRestGetter();
      UsernamePasswordCredentials usernamePasswordCredentials0 = new UsernamePasswordCredentials();
      dummyRestGetter0.setCredentials(usernamePasswordCredentials0);
  }
}
