/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.core.nw7;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.core.CoreException;
import com.sap.netweaver.porta.core.nw7.DeployManagerImpl;
import com.sap.netweaver.porta.core.nw7.LifecycleManagerImpl;
import com.sap.netweaver.porta.core.nw7.ServerImpl;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestServerImpl {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ServerImpl serverImpl0 = new ServerImpl("%@5T,uMQI", (-2));
      // Undeclared exception!
      try {
        serverImpl0.ping();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.apache.axis.client.AxisClient
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ServerImpl serverImpl0 = new ServerImpl((String) null, (-12));
      DeployManagerImpl deployManagerImpl0 = (DeployManagerImpl)serverImpl0.getDeployManager();
      DeployManagerImpl deployManagerImpl1 = (DeployManagerImpl)serverImpl0.getDeployManager();
      assertSame(deployManagerImpl1, deployManagerImpl0);
      assertNotNull(deployManagerImpl1);
  }

  @Test
  public void test2()  throws Throwable  {
      ServerImpl serverImpl0 = new ServerImpl("%@5T,uMQI", (-2));
      LifecycleManagerImpl lifecycleManagerImpl0 = (LifecycleManagerImpl)serverImpl0.getLifecycleManager();
      LifecycleManagerImpl lifecycleManagerImpl1 = (LifecycleManagerImpl)serverImpl0.getLifecycleManager();
      assertNotNull(lifecycleManagerImpl1);
      assertSame(lifecycleManagerImpl1, lifecycleManagerImpl0);
  }
}
