/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.core.nw7;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.core.CoreException;
import com.sap.netweaver.porta.core.NotAuthorizedException;
import com.sap.netweaver.porta.core.nw7.LifecycleManagerImpl;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestLifecycleManagerImpl {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LifecycleManagerImpl lifecycleManagerImpl0 = new LifecycleManagerImpl("#>U$e\"<7rcOAz", 181);
      // Undeclared exception!
      try {
        lifecycleManagerImpl0.enableDebugging();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.apache.axis.client.AxisClient
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      LifecycleManagerImpl lifecycleManagerImpl0 = new LifecycleManagerImpl("$w|g", (-7));
      // Undeclared exception!
      try {
        lifecycleManagerImpl0.disableDebugging("$w|g");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.apache.axis.client.AxisClient
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      LifecycleManagerImpl lifecycleManagerImpl0 = new LifecycleManagerImpl("\"%>R.P,m9yV", (-1));
      // Undeclared exception!
      try {
        lifecycleManagerImpl0.stop();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.apache.axis.client.AxisClient
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      LifecycleManagerImpl lifecycleManagerImpl0 = new LifecycleManagerImpl("{aI\"]M[d(H7u'", 1005);
      // Undeclared exception!
      try {
        lifecycleManagerImpl0.start();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.apache.axis.client.AxisClient
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      LifecycleManagerImpl lifecycleManagerImpl0 = new LifecycleManagerImpl("Tzb)!D%p9pO&5jL", 6);
      // Undeclared exception!
      try {
        lifecycleManagerImpl0.getState();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.apache.axis.client.AxisClient
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      LifecycleManagerImpl lifecycleManagerImpl0 = new LifecycleManagerImpl("tR=", 1);
      // Undeclared exception!
      try {
        lifecycleManagerImpl0.restart();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.apache.axis.client.AxisClient
         */
      }
  }
}
