/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.core.nw7;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.engine.services.dc.wsgate.Application;
import com.sap.engine.services.dc.wsgate.DeployResult;
import com.sap.netweaver.porta.core.CoreException;
import com.sap.netweaver.porta.core.nw7.ApplicationImpl;
import com.sap.netweaver.porta.core.nw7.DMUtilsImpl;
import com.sap.netweaver.porta.core.nw7.FileUploaderImpl;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.rpc.ServiceException;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDMUtilsImpl {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DMUtilsImpl dMUtilsImpl0 = new DMUtilsImpl();
      Application[] applicationArray0 = new Application[10];
      com.sap.netweaver.porta.core.Application[] applicationArray1 = dMUtilsImpl0.convertApplications(applicationArray0);
      assertNotNull(applicationArray1);
  }

  @Test
  public void test1()  throws Throwable  {
      DMUtilsImpl dMUtilsImpl0 = new DMUtilsImpl();
      FileUploaderImpl fileUploaderImpl0 = (FileUploaderImpl)dMUtilsImpl0.getFileUploader("", 30);
      assertNotNull(fileUploaderImpl0);
  }

  @Test
  public void test2()  throws Throwable  {
      DMUtilsImpl dMUtilsImpl0 = new DMUtilsImpl();
      // Undeclared exception!
      try {
        dMUtilsImpl0.convertDeployResult((DeployResult) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      DMUtilsImpl dMUtilsImpl0 = new DMUtilsImpl();
      URL uRL0 = dMUtilsImpl0.getDeployWSUrl("0b2k.avpx,*97NA", 97);
      // Undeclared exception!
      try {
        dMUtilsImpl0.getDeployWSProxy(uRL0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.apache.axis.client.AxisClient
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      DMUtilsImpl dMUtilsImpl0 = new DMUtilsImpl();
      com.sap.netweaver.porta.core.Application[] applicationArray0 = new com.sap.netweaver.porta.core.Application[7];
      ApplicationImpl applicationImpl0 = new ApplicationImpl((Application) null);
      applicationArray0[0] = (com.sap.netweaver.porta.core.Application) applicationImpl0;
      applicationArray0[1] = (com.sap.netweaver.porta.core.Application) applicationImpl0;
      applicationArray0[2] = (com.sap.netweaver.porta.core.Application) applicationImpl0;
      applicationArray0[3] = (com.sap.netweaver.porta.core.Application) applicationImpl0;
      applicationArray0[4] = (com.sap.netweaver.porta.core.Application) applicationImpl0;
      applicationArray0[5] = applicationArray0[4];
      applicationArray0[6] = applicationArray0[2];
      Application[] applicationArray1 = dMUtilsImpl0.convertApplications(applicationArray0);
      assertNotNull(applicationArray1);
  }

  @Test
  public void test5()  throws Throwable  {
      DMUtilsImpl dMUtilsImpl0 = new DMUtilsImpl();
      File[] fileArray0 = new File[1];
      File file0 = new File((File) null, "@HW");
      fileArray0[0] = file0;
      String[] stringArray0 = dMUtilsImpl0.getAsArchivePaths(fileArray0);
      assertNotNull(stringArray0);
  }

  @Test
  public void test6()  throws Throwable  {
      DMUtilsImpl dMUtilsImpl0 = new DMUtilsImpl();
      File[] fileArray0 = new File[6];
      // Undeclared exception!
      try {
        dMUtilsImpl0.getAsArchiveFiles(fileArray0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
