/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.ide.eclipse.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.ide.eclipse.util.FacetUtil;
import org.eclipse.wst.common.project.facet.core.IFacetedProject;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class FacetUtilEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        FacetUtil.hasProjectFacet((IFacetedProject) null, (String) null, (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.eclipse.wst.common.project.facet.core.ProjectFacetsManager
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      FacetUtil facetUtil0 = new FacetUtil();
      assertNotNull(facetUtil0);
  }
}
