/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.saphostcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.saphostcontrol.OperationResult;
import com.sap.managementconsole.soap.axis.saphostcontrol.ResponseMessage;
import javax.xml.namespace.QName;
import org.apache.axis.description.TypeDesc;
import org.apache.axis.encoding.ser.BeanDeserializer;
import org.apache.axis.encoding.ser.BeanSerializer;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class OperationResultEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      OperationResult operationResult0 = new OperationResult();
      operationResult0.setMOperationID("");
      OperationResult operationResult1 = new OperationResult();
      boolean boolean0 = operationResult0.equals((Object) operationResult1);
      assertEquals(false, boolean0);
      assertFalse(operationResult1.equals(operationResult0));
  }

  @Test
  public void test1()  throws Throwable  {
      ResponseMessage[] responseMessageArray0 = new ResponseMessage[32];
      OperationResult operationResult0 = new OperationResult((String) null, responseMessageArray0);
      operationResult0.setMOperationResults(responseMessageArray0);
      assertNull(operationResult0.getMOperationID());
  }

  @Test
  public void test2()  throws Throwable  {
      OperationResult operationResult0 = new OperationResult();
      OperationResult operationResult1 = new OperationResult();
      boolean boolean0 = operationResult0.equals((Object) operationResult1);
      assertEquals(true, boolean0);
  }

  @Test
  public void test3()  throws Throwable  {
      TypeDesc typeDesc0 = OperationResult.getTypeDesc();
      assertEquals(false, typeDesc0.hasAttributes());
  }

  @Test
  public void test4()  throws Throwable  {
      Class<?> class0 = OperationResult.class;
      QName qName0 = new QName("", "", "");
      BeanSerializer beanSerializer0 = (BeanSerializer)OperationResult.getSerializer("", (Class) class0, qName0);
      assertEquals("Axis SAX Mechanism", beanSerializer0.getMechanismType());
  }

  @Test
  public void test5()  throws Throwable  {
      Class<?> class0 = OperationResult.class;
      QName qName0 = new QName("", "", "");
      BeanDeserializer beanDeserializer0 = (BeanDeserializer)OperationResult.getDeserializer("", (Class) class0, qName0);
      assertEquals("Axis SAX Mechanism", beanDeserializer0.getMechanismType());
  }

  @Test
  public void test6()  throws Throwable  {
      OperationResult operationResult0 = new OperationResult();
      Object object0 = new Object();
      boolean boolean0 = operationResult0.equals(object0);
      assertEquals(false, boolean0);
  }

  @Test
  public void test7()  throws Throwable  {
      OperationResult operationResult0 = new OperationResult();
      ResponseMessage[] responseMessageArray0 = new ResponseMessage[16];
      OperationResult operationResult1 = new OperationResult((String) null, responseMessageArray0);
      boolean boolean0 = operationResult0.equals((Object) operationResult1);
      assertEquals(false, boolean0);
      assertFalse(operationResult1.equals(operationResult0));
  }

  @Test
  public void test8()  throws Throwable  {
      ResponseMessage[] responseMessageArray0 = new ResponseMessage[32];
      OperationResult operationResult0 = new OperationResult((String) null, responseMessageArray0);
      OperationResult operationResult1 = new OperationResult("n", responseMessageArray0);
      boolean boolean0 = operationResult0.equals((Object) operationResult1);
      assertFalse(operationResult1.equals(operationResult0));
      assertEquals(false, boolean0);
  }

  @Test
  public void test9()  throws Throwable  {
      ResponseMessage[] responseMessageArray0 = new ResponseMessage[12];
      OperationResult operationResult0 = new OperationResult(": GL(L@#d", responseMessageArray0);
      OperationResult operationResult1 = new OperationResult(": GL(L@#d", responseMessageArray0);
      boolean boolean0 = operationResult0.equals((Object) operationResult1);
      assertEquals(true, boolean0);
  }

  @Test
  public void test10()  throws Throwable  {
      ResponseMessage[] responseMessageArray0 = new ResponseMessage[32];
      OperationResult operationResult0 = new OperationResult((String) null, responseMessageArray0);
      ResponseMessage[] responseMessageArray1 = new ResponseMessage[16];
      OperationResult operationResult1 = new OperationResult((String) null, responseMessageArray1);
      boolean boolean0 = operationResult0.equals((Object) operationResult1);
      assertEquals(false, boolean0);
  }

  @Test
  public void test11()  throws Throwable  {
      OperationResult operationResult0 = new OperationResult();
      int int0 = operationResult0.hashCode();
      assertEquals(1, int0);
  }

  @Test
  public void test12()  throws Throwable  {
      ResponseMessage[] responseMessageArray0 = new ResponseMessage[10];
      ResponseMessage responseMessage0 = new ResponseMessage("XP@%M5arS*9D(", "XP@%M5arS*9D(");
      responseMessageArray0[6] = responseMessage0;
      OperationResult operationResult0 = new OperationResult("XP@%M5arS*9D(", responseMessageArray0);
      int int0 = operationResult0.hashCode();
      assertEquals((-1964875438), int0);
  }
}
