/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.saphostcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.saphostcontrol.CancelOperationType;
import java.io.ObjectStreamException;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestCancelOperationType {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        CancelOperationType.fromString("");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.CancelOperationType
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Class<?> class0 = CancelOperationType.class;
      // Undeclared exception!
      try {
        CancelOperationType.getDeserializer("h7xF7/G(E", (Class) class0, (QName) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.CancelOperationType
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try {
        CancelOperationType.fromString("");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.CancelOperationType
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try {
        CancelOperationType.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.CancelOperationType
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      Class<?> class0 = CancelOperationType.class;
      QName qName0 = new QName("7!", "7!");
      // Undeclared exception!
      try {
        CancelOperationType.getSerializer("7!", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.CancelOperationType
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try {
        CancelOperationType.fromString("");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.CancelOperationType
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      CancelOperationType cancelOperationType0 = null;
      try {
        cancelOperationType0 = new CancelOperationType("h7xF7/G(E");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.CancelOperationType
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try {
        CancelOperationType.fromString("eD2%IR7z~9W]..3cadq");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.CancelOperationType
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      CancelOperationType cancelOperationType0 = null;
      try {
        cancelOperationType0 = CancelOperationType.value1;
      } catch(NoClassDefFoundError e) {}
  }
}
