/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.saphostcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.saphostcontrol.ACOperation;
import com.sap.managementconsole.soap.axis.saphostcontrol.ACOperationArguments;
import com.sap.managementconsole.soap.axis.saphostcontrol.ACOperationCode;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestACOperation {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Class<?> class0 = QName.class;
      QName qName0 = new QName("AC-OP-IFDOWN", "AC-OP-IFDOWN");
      // Undeclared exception!
      try {
        ACOperation.getSerializer("AC-OP-IFDOWN", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.ACOperation
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ACOperation aCOperation0 = null;
      try {
        aCOperation0 = new ACOperation();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.ACOperation
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try {
        ACOperation.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.ACOperation
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      ACOperation aCOperation0 = null;
      try {
        aCOperation0 = new ACOperation();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.ACOperation
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      QName qName0 = new QName("", "");
      Class<?> class0 = ACOperationCode.class;
      // Undeclared exception!
      try {
        ACOperation.getDeserializer("", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.ACOperation
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      ACOperation aCOperation0 = null;
      try {
        aCOperation0 = new ACOperation();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.ACOperation
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      ACOperation aCOperation0 = null;
      try {
        aCOperation0 = new ACOperation();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.ACOperation
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      ACOperation aCOperation0 = null;
      try {
        aCOperation0 = new ACOperation();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.ACOperation
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      ACOperation aCOperation0 = null;
      try {
        aCOperation0 = new ACOperation();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.ACOperation
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      ACOperation aCOperation0 = null;
      try {
        aCOperation0 = new ACOperation();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.ACOperation
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      ACOperation aCOperation0 = null;
      try {
        aCOperation0 = new ACOperation();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.ACOperation
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      ACOperation aCOperation0 = null;
      try {
        aCOperation0 = new ACOperation();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.ACOperation
         */
      }
  }
}
