/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.saphostcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.saphostcontrol.InstanceOptionsFlags;
import com.sap.managementconsole.soap.axis.saphostcontrol.OperationOptions;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestOperationOptions {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        OperationOptions.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationOptions
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Class<?> class0 = Object.class;
      // Undeclared exception!
      try {
        OperationOptions.getSerializer("Xa-cYw8?8+RK6cx(6T", (Class) class0, (QName) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationOptions
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      InstanceOptionsFlags[] instanceOptionsFlagsArray0 = new InstanceOptionsFlags[5];
      OperationOptions operationOptions0 = null;
      try {
        operationOptions0 = new OperationOptions();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationOptions
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      Class<?> class0 = Object.class;
      // Undeclared exception!
      try {
        OperationOptions.getDeserializer("Xa-cYw8?8+RK6cx(6T", (Class) class0, (QName) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationOptions
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      OperationOptions operationOptions0 = null;
      try {
        operationOptions0 = new OperationOptions();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationOptions
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      OperationOptions operationOptions0 = null;
      try {
        operationOptions0 = new OperationOptions();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationOptions
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      InstanceOptionsFlags[] instanceOptionsFlagsArray0 = new InstanceOptionsFlags[11];
      OperationOptions operationOptions0 = null;
      try {
        operationOptions0 = new OperationOptions();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationOptions
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      InstanceOptionsFlags[] instanceOptionsFlagsArray0 = new InstanceOptionsFlags[2];
      OperationOptions operationOptions0 = null;
      try {
        operationOptions0 = new OperationOptions((-10L), instanceOptionsFlagsArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationOptions
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      InstanceOptionsFlags[] instanceOptionsFlagsArray0 = new InstanceOptionsFlags[5];
      OperationOptions operationOptions0 = null;
      try {
        operationOptions0 = new OperationOptions();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationOptions
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      OperationOptions operationOptions0 = null;
      try {
        operationOptions0 = new OperationOptions();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationOptions
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      InstanceOptionsFlags[] instanceOptionsFlagsArray0 = new InstanceOptionsFlags[3];
      OperationOptions operationOptions0 = null;
      try {
        operationOptions0 = new OperationOptions();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationOptions
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      InstanceOptionsFlags[] instanceOptionsFlagsArray0 = new InstanceOptionsFlags[11];
      InstanceOptionsFlags instanceOptionsFlags0 = null;
      try {
        instanceOptionsFlags0 = InstanceOptionsFlags.value2;
      } catch(NoClassDefFoundError e) {}
  }
}
