/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.saphostcontrol;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.saphostcontrol.OperationCode;
import java.io.ObjectStreamException;
import javax.xml.namespace.QName;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestOperationCode {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        OperationCode.fromValue("");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationCode
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try {
        OperationCode.fromString("OPERATION-STOP");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationCode
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      OperationCode operationCode0 = null;
      try {
        operationCode0 = new OperationCode("OPERATION-STOP");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationCode
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      Class<?> class0 = OperationCode.class;
      // Undeclared exception!
      try {
        OperationCode.getDeserializer("", (Class) class0, (QName) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationCode
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try {
        OperationCode.fromValue("");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationCode
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try {
        OperationCode.getTypeDesc();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationCode
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      QName qName0 = new QName("8", "8");
      Class<?> class0 = OperationCode.class;
      // Undeclared exception!
      try {
        OperationCode.getSerializer("8", (Class) class0, qName0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationCode
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      OperationCode operationCode0 = null;
      try {
        operationCode0 = OperationCode.value1;
      } catch(NoClassDefFoundError e) {}
  }

  @Test
  public void test8()  throws Throwable  {
      // Undeclared exception!
      try {
        OperationCode.fromValue("\".");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class com.sap.managementconsole.soap.axis.saphostcontrol.OperationCode
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      OperationCode operationCode0 = null;
      try {
        operationCode0 = OperationCode.value2;
      } catch(NoClassDefFoundError e) {}
  }
}
