/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.core.mock;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.core.DeployResultStatus;
import com.sap.netweaver.porta.core.mock.DeployResultMock;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class DeployResultMockEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DeployResultStatus deployResultStatus0 = DeployResultStatus.UNKNOWN;
      DeployResultMock deployResultMock0 = new DeployResultMock(deployResultStatus0, (String) null);
      DeployResultStatus deployResultStatus1 = deployResultMock0.getStatus();
      assertSame(deployResultStatus1, deployResultStatus0);
  }

  @Test
  public void test1()  throws Throwable  {
      DeployResultStatus deployResultStatus0 = DeployResultStatus.UNKNOWN;
      DeployResultMock deployResultMock0 = new DeployResultMock(deployResultStatus0, "~o 7s%FGW66G#Iw e,");
      String string0 = deployResultMock0.getStatusDetails();
      assertEquals("~o 7s%FGW66G#Iw e,", string0);
  }
}
