/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.core.mock;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.core.CoreException;
import com.sap.netweaver.porta.core.NotAuthorizedException;
import com.sap.netweaver.porta.core.mock.DeployManagerMock;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class DeployManagerMockEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DeployManagerMock deployManagerMock0 = new DeployManagerMock();
      try {
        deployManagerMock0.getApplications();
        fail("Expecting exception: NotAuthorizedException");
      } catch(NotAuthorizedException e) {
      }
  }
}
