/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.core.mock;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.core.CoreException;
import com.sap.netweaver.porta.core.DebugSessionInfo;
import com.sap.netweaver.porta.core.NotAuthorizedException;
import com.sap.netweaver.porta.core.ServerState;
import com.sap.netweaver.porta.core.mock.LifecycleManagerMock;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class LifecycleManagerMockEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LifecycleManagerMock lifecycleManagerMock0 = new LifecycleManagerMock();
      DebugSessionInfo debugSessionInfo0 = lifecycleManagerMock0.enableDebugging();
      assertNull(debugSessionInfo0);
  }

  @Test
  public void test1()  throws Throwable  {
      LifecycleManagerMock lifecycleManagerMock0 = new LifecycleManagerMock();
      ServerState serverState0 = lifecycleManagerMock0.getState();
      assertEquals("Stopped", serverState0.toString());
  }

  @Test
  public void test2()  throws Throwable  {
      LifecycleManagerMock lifecycleManagerMock0 = new LifecycleManagerMock();
      lifecycleManagerMock0.disableDebugging("77B");
      assertEquals(ServerState.STOPPED, lifecycleManagerMock0.getState());
  }
}
