/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.core.mock;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.core.CoreException;
import com.sap.netweaver.porta.core.mock.DeployManagerMock;
import com.sap.netweaver.porta.core.mock.LifecycleManagerMock;
import com.sap.netweaver.porta.core.mock.ServerMock;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.evosuite.Properties.SandboxMode;
import org.evosuite.sandbox.Sandbox;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestServerMock {

  private static ExecutorService executor; 

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
    org.evosuite.Properties.SANDBOX_MODE = SandboxMode.RECOMMENDED; 
    Sandbox.initializeSecurityManagerForSUT(); 
    executor = Executors.newCachedThreadPool(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    executor.shutdownNow(); 
    Sandbox.resetDefaultSecurityManager(); 
  } 

  @Before 
  public void initTestCase(){ 
    Sandbox.goingToExecuteSUTCode(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    Sandbox.doneWithExecutingSUTCode(); 
  } 


  @Test
  public void test0()  throws Throwable  {
      ServerMock serverMock0 = new ServerMock();
      String string0 = serverMock0.getSystemName();
      assertEquals("MCK", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      ServerMock serverMock0 = new ServerMock();
      serverMock0.ping();
      assertEquals("MCK", serverMock0.getSystemName());
  }

  @Test
  public void test2()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
        try {
          ServerMock serverMock0 = new ServerMock();
          // Undeclared exception!
          try {
            serverMock0.getHttpAccessPoint();
            fail("Expecting exception: SecurityException");
          } catch(SecurityException e) {
            /*
             * Security manager blocks (\"java.net.SocketPermission\" \"localhost\" \"resolve\")
             * java.lang.Thread.getStackTrace(Thread.java:1567)
             * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
             * java.lang.SecurityManager.checkConnect(SecurityManager.java:1048)
             * java.net.InetAddress.getAllByName0(InetAddress.java:1203)
             * java.net.InetAddress.getAllByName(InetAddress.java:1127)
             * java.net.InetAddress.getAllByName(InetAddress.java:1063)
             * java.net.InetAddress.getByName(InetAddress.java:1013)
             * java.net.InetSocketAddress.<init>(InetSocketAddress.java:142)
             * com.sap.netweaver.porta.core.mock.ServerMock.getHttpAccessPoint(ServerMock.java:48)
             * sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             * sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
             * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             * java.lang.reflect.Method.invoke(Method.java:601)
             * org.evosuite.testcase.MethodStatement$1.execute(MethodStatement.java:262)
             * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
             * org.evosuite.testcase.MethodStatement.execute(MethodStatement.java:217)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:44)
             * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
             * java.util.concurrent.FutureTask.run(FutureTask.java:166)
             * java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
             * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
             * java.lang.Thread.run(Thread.java:722)
             */
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test3()  throws Throwable  {
      ServerMock serverMock0 = new ServerMock();
      LifecycleManagerMock lifecycleManagerMock0 = (LifecycleManagerMock)serverMock0.getLifecycleManager();
      LifecycleManagerMock lifecycleManagerMock1 = (LifecycleManagerMock)serverMock0.getLifecycleManager();
      assertSame(lifecycleManagerMock1, lifecycleManagerMock0);
      assertNotNull(lifecycleManagerMock1);
  }

  @Test
  public void test4()  throws Throwable  {
      ServerMock serverMock0 = new ServerMock();
      DeployManagerMock deployManagerMock0 = (DeployManagerMock)serverMock0.getDeployManager();
      DeployManagerMock deployManagerMock1 = (DeployManagerMock)serverMock0.getDeployManager();
      assertSame(deployManagerMock1, deployManagerMock0);
      assertNotNull(deployManagerMock1);
  }
}
