/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.ide.eclipse;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.ide.eclipse.SapNWPlugin;
import org.eclipse.core.runtime.Path;
import org.evosuite.testcase.CodeUnderTestException;
import org.osgi.framework.BundleContext;

@RunWith(EvoSuiteRunner.class)
public class SapNWPluginEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      SapNWPlugin sapNWPlugin0 = new SapNWPlugin();
      assertEquals(false, sapNWPlugin0.isDebugging());
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.stop(Lorg/osgi/framework/BundleContext;)V: root-Branch
   * 2 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.getDefault()Lcom/sap/netweaver/porta/ide/eclipse/SapNWPlugin;: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      SapNWPlugin sapNWPlugin0 = SapNWPlugin.getDefault();
      sapNWPlugin0.stop((BundleContext) null);
      assertEquals(false, sapNWPlugin0.isDebugging());
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.start(Lorg/osgi/framework/BundleContext;)V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      SapNWPlugin.getDefault();
      Path path0 = Path.EMPTY;
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * 1 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.log(Lorg/eclipse/core/runtime/IStatus;)V: root-Branch
   * 2 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.logError(Ljava/lang/String;Ljava/lang/Throwable;)V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      Throwable throwable0 = new Throwable();
      // Undeclared exception!
      try {
        SapNWPlugin.logError("C?7", throwable0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.errorDialog(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * 2 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.errorDialog(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)V: I21 Branch 1 IFNULL L68 - false
   */
  @Test
  public void test4()  throws Throwable  {
      Throwable throwable0 = new Throwable("79u$J^:H{A");
      // Undeclared exception!
      try {
        SapNWPlugin.errorDialog("79u$J^:H{A", "79u$J^:H{A", throwable0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.eclipse.swt.internal.wpf.COM
         */
      }
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.logInfo(Ljava/lang/String;Ljava/lang/Throwable;)V: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try {
        SapNWPlugin.logInfo("=Bm|ni", (Throwable) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 6
  /*
   * 3 covered goals:
   * 1 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.logWarning(Ljava/lang/String;Ljava/lang/Throwable;)V: root-Branch
   * 2 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.getDefault()Lcom/sap/netweaver/porta/ide/eclipse/SapNWPlugin;: root-Branch
   * 3 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.log(Lorg/eclipse/core/runtime/IStatus;)V: root-Branch
   */
  @Test
  public void test6()  throws Throwable  {
      Throwable throwable0 = new Throwable("hpux", (Throwable) null);
      // Undeclared exception!
      try {
        SapNWPlugin.logWarning("hpux", throwable0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 7
  /*
   * 2 covered goals:
   * 1 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.errorDialog(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)V: I21 Branch 1 IFNULL L68 - true
   * 2 com.sap.netweaver.porta.ide.eclipse.SapNWPlugin.errorDialog(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try {
        SapNWPlugin.errorDialog("V%]r1Z)!B`V,", "V%]r1Z)!B`V,", (Throwable) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.eclipse.swt.internal.wpf.COM
         */
      }
  }
}
