/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.managementconsole.soap.axis.sapcontrol.holders;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.managementconsole.soap.axis.sapcontrol.Alert;
import com.sap.managementconsole.soap.axis.sapcontrol.holders.ArrayOfAlertHolder;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestArrayOfAlertHolder {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ArrayOfAlertHolder arrayOfAlertHolder0 = new ArrayOfAlertHolder((Alert[]) null);
      assertNotNull(arrayOfAlertHolder0);
  }

  @Test
  public void test1()  throws Throwable  {
      ArrayOfAlertHolder arrayOfAlertHolder0 = new ArrayOfAlertHolder();
      assertNotNull(arrayOfAlertHolder0);
  }
}
