/*******************************************************************************
 * Copyright (c) 2009, 2010 SAP AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Kaloyan Raev (SAP AG) - initial API and implementation
 *******************************************************************************/
package com.sap.netweaver.porta.core;

/**
 * Represents a Java EE application deployed on the server.
 * 
 * <p>
 * This is a stateless object that represents that last state of the
 * corresponding Java EE application by the time the object was generated by a
 * deployment method. This means that calling the methods of this class may
 * return you an out dated information about the Java EE application. If you
 * need an up to date information about the application you should request a
 * suitable deployment method that will generate you new
 * <code>Application</code> object for this Java EE application.
 * </p>
 */
public interface Application {

	/**
	 * Returns a unique identification of the application.
	 * 
	 * @return a string representation of the application ID.
	 */
	public String getId();

	/**
	 * Returns the name of the application.
	 * 
	 * @return a string of the application name.
	 */
	public String getName();

	/**
	 * Returns the vendor of the application.
	 * 
	 * @return a string representation of the application vendor.
	 */
	public String getVendor();

	/**
	 * Returns the version of the application.
	 * 
	 * @return a string representation of the application version.
	 */
	public String getVersion();

	/**
	 * Returns the location of the application.
	 * 
	 * @return a string representation of the application location.
	 */
	public String getLocation();

	/**
	 * Returns the current application status.
	 * 
	 * @return a <code>ApplicationStatus</code> enumeration value that
	 *         represents the current status of the application.
	 * 
	 * @see ApplicationStatus
	 */
	public ApplicationStatus getStatus();

}
