/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.ide.eclipse.server.ui.editor;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.ide.eclipse.server.ui.editor.SapNWInstanceEditorSection;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.ui.IEditorInput;
import org.eclipse.ui.IEditorSite;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestSapNWInstanceEditorSection {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SapNWInstanceEditorSection sapNWInstanceEditorSection0 = new SapNWInstanceEditorSection();
      // Undeclared exception!
      try {
        sapNWInstanceEditorSection0.createSection((Composite) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      SapNWInstanceEditorSection sapNWInstanceEditorSection0 = new SapNWInstanceEditorSection();
      sapNWInstanceEditorSection0.init((IEditorSite) null, (IEditorInput) null);
      assertNull(sapNWInstanceEditorSection0.getErrorMessage());
  }
}
