/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.lavalamp.device;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sf.lavalamp.device.DummyDevice;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDummyDevice {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DummyDevice dummyDevice0 = new DummyDevice();
      dummyDevice0.turnOff();
      assertEquals("dummy device null", dummyDevice0.toString());
  }

  @Test
  public void test1()  throws Throwable  {
      DummyDevice dummyDevice0 = new DummyDevice();
      dummyDevice0.init();
      assertEquals("dummy device null", dummyDevice0.toString());
  }
}
