/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.lavalamp.device;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sf.lavalamp.Pause;
import net.sf.lavalamp.device.Blink;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestBlink {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Blink blink0 = new Blink();
      Pause pause0 = new Pause();
      blink0.setPause(pause0);
  }
}
